name: Compile and Release Sketch

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
    tags:
      - 'v*'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install arduino-cli
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform and library
        run: make install-deps

      - name: Compile
        run: make compile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arduino-binaries
          path: |
            build/*.hex
            build/*.elf

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: arduino-binaries
          path: build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.hex
            build/*.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
