name: Compile Sketch

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install arduino-cli
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform and library
        run: make install-deps

      - name: Compile
        run: make compile
